# Generated by Django 5.2 on 2025-05-29 06:48

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scaduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('trama', models.TextField()),
                ('anno_pubblicazione', models.IntegerField()),
                ('editore', models.CharField(max_length=100)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('genere', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('fantasy', 'Fantasy'), ('thriller', 'Thriller'), ('romance', 'Romance')], max_length=100)),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
