# Generated by Django 5.2 on 2025-05-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaduti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scaduto',
            name='numero_pagine',
            field=models.IntegerField(default=1),
        ),
    ]
